version: "3"

services:
  workshop-front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api
    networks:
      - workshop-network
    container_name: workshop-front
    command: npm run dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - workshop-network
    depends_on:
      - workshop-front

networks:
  workshop-network:
    driver: bridge
    external: true
